pekko.actor.allow-java-serialization = off

pekko.actor.serializers {
  payment-event = "com.paymentprocessing.runtime.pekko.payment.PaymentEventSerializer"
}

pekko.actor.serialization-bindings {
  "com.paymentprocessing.domain.payment.PaymentEvent" = payment-event
}
